//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSCD_WEB.UserControl.ViTri {
    
    
    public partial class ucViTri_BreadCrumb {
        
        /// <summary>
        /// ucTimKiem_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.TimKiem.ucTimKiem ucTimKiem_Mobile;
        
        /// <summary>
        /// Label_TenViTri control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::System.Web.UI.WebControls.Label Label_TenViTri;
        
        /// <summary>
        /// ucTimKiem_Web control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.TimKiem.ucTimKiem ucTimKiem_Web;
    }
}
