//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSCD_WEB {
    
    
    public partial class LoaiPhong {
        
        /// <summary>
        /// ucLoaiPhong_Web control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.LoaiPhong.ucLoaiPhong_Web ucLoaiPhong_Web;
        
        /// <summary>
        /// ucLoaiPhong_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.LoaiPhong.ucLoaiPhong_Mobile ucLoaiPhong_Mobile;
        
        /// <summary>
        /// ucFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.Footer.ucFooter ucFooter;
    }
}
