//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSCD_WEB {
    
    
    public partial class ViTri {
        
        /// <summary>
        /// ucViTri_Web control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.ViTri.ucViTri_Web ucViTri_Web;
        
        /// <summary>
        /// ucViTri_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.ViTri.ucViTri_Mobile ucViTri_Mobile;
        
        /// <summary>
        /// ucFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TSCD_WEB.UserControl.Footer.ucFooter ucFooter;
    }
}
