//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLPH {
    
    
    public partial class PhongThietBi {
        
        /// <summary>
        /// Panel_Web control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel_Web;
        
        /// <summary>
        /// _ucPhongThietBi_Web control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebQLPH.UserControl.PhongThietBi.ucPhongThietBi_Web _ucPhongThietBi_Web;
        
        /// <summary>
        /// Panel_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel_Mobile;
        
        /// <summary>
        /// _ucPhongThietBi_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebQLPH.UserControl.PhongThietBi.ucPhongThietBi_Mobile _ucPhongThietBi_Mobile;
    }
}
