// <auto-generated />
namespace TSCD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class bosung_dinhNghiaLaiSuTangGiamTaiSan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bosung_dinhNghiaLaiSuTangGiamTaiSan));
        
        string IMigrationMetadata.Id
        {
            get { return "201410020610142_bosung_dinhNghiaLaiSuTangGiamTaiSan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
