// <auto-generated />
namespace TSCD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ThayLoaiTaiSan_SoNamSD_bangPhanTramhaoMon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThayLoaiTaiSan_SoNamSD_bangPhanTramhaoMon));
        
        string IMigrationMetadata.Id
        {
            get { return "201411280419524_ThayLoaiTaiSan_SoNamSD_bangPhanTramhaoMon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
