// <auto-generated />
namespace TSCD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class rollback_LogHeThong_PrimaryKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rollback_LogHeThong_PrimaryKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201409061514123_rollback_LogHeThong_PrimaryKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
