// <auto-generated />
namespace TSCD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class them_nuoc_san_xuat_choTaiSan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_nuoc_san_xuat_choTaiSan));
        
        string IMigrationMetadata.Id
        {
            get { return "201409242349347_them_nuoc_san_xuat_choTaiSan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
