// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class bo_rang_buoc_path_hinhanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bo_rang_buoc_path_hinhanh));
        
        string IMigrationMetadata.Id
        {
            get { return "201406211025184_bo_rang_buoc_path_hinhanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
