// <auto-generated />
namespace PTB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class doi_khoachinh_LOGHETHONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doi_khoachinh_LOGHETHONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201409050526584_doi_khoachinh_LOGHETHONG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
