// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class hopTheGiangVienVaQuanTriVien_phanBietTheoGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hopTheGiangVienVaQuanTriVien_phanBietTheoGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201408190516231_hopTheGiangVienVaQuanTriVien_phanBietTheoGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
