// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DoiTenLOGTINHTRANG_LOGTHIETBI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoiTenLOGTINHTRANG_LOGTHIETBI));
        
        string IMigrationMetadata.Id
        {
            get { return "201406200410362_DoiTenLOGTINHTRANG_LOGTHIETBI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
