// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class boNgayLapTrongThietBi_ChuyenQuaCTTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(boNgayLapTrongThietBi_ChuyenQuaCTTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201407180311147_boNgayLapTrongThietBi_ChuyenQuaCTTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
