// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class them_rang_buoc_unique_choLOGTHIETBI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_rang_buoc_unique_choLOGTHIETBI));
        
        string IMigrationMetadata.Id
        {
            get { return "201406200349510_them_rang_buoc_unique_choLOGTHIETBI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
