// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mot_entity_co_nhieuhinhanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mot_entity_co_nhieuhinhanh));
        
        string IMigrationMetadata.Id
        {
            get { return "201406161322533_mot_entity_co_nhieuhinhanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
