// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class chuyen_thuoctinh_ngay_LOGSUCO_SUCO_goboMotVaiIndex_K_canthiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chuyen_thuoctinh_ngay_LOGSUCO_SUCO_goboMotVaiIndex_K_canthiet));
        
        string IMigrationMetadata.Id
        {
            get { return "201407170907134_chuyen_thuoctinh_ngay_LOGSUCO_SUCO_goboMotVaiIndex_K_canthiet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
