// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class sua_thuoc_tinh_phieumuonphong_lydotuchoi_thanh_ghichu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_thuoc_tinh_phieumuonphong_lydotuchoi_thanh_ghichu));
        
        string IMigrationMetadata.Id
        {
            get { return "201408050717108_sua_thuoc_tinh_phieumuonphong_lydotuchoi_thanh_ghichu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
