// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class them_truong_order_vao_coso_tudong_lay_id_quasaukhiADD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_truong_order_vao_coso_tudong_lay_id_quasaukhiADD));
        
        string IMigrationMetadata.Id
        {
            get { return "201406300429493_them_truong_order_vao_coso_tudong_lay_id_quasaukhiADD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
