// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class them_rangbuoc_xoa_cs_xoaluonvitri_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_rangbuoc_xoa_cs_xoaluonvitri_));
        
        string IMigrationMetadata.Id
        {
            get { return "201406260644132_them_rangbuoc_xoa_cs_xoaluonvitri_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
