// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class them_nghiepvu_muonphong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_nghiepvu_muonphong));
        
        string IMigrationMetadata.Id
        {
            get { return "201408040646276_them_nghiepvu_muonphong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
