// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class them_thuoc_tinh_khoaphongmuon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_thuoc_tinh_khoaphongmuon));
        
        string IMigrationMetadata.Id
        {
            get { return "201408050612322_them_thuoc_tinh_khoaphongmuon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
