// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class them_dinh_nghia_ve_permission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_dinh_nghia_ve_permission));
        
        string IMigrationMetadata.Id
        {
            get { return "201408180445382_them_dinh_nghia_ve_permission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
