// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class go_rangbuoc_trong_Setting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(go_rangbuoc_trong_Setting));
        
        string IMigrationMetadata.Id
        {
            get { return "201407210442427_go_rangbuoc_trong_Setting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
