// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class chinh_sua_su_co_phong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chinh_sua_su_co_phong));
        
        string IMigrationMetadata.Id
        {
            get { return "201408060750152_chinh_sua_su_co_phong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
