// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class gobo_rangbuoc_tenphong_unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gobo_rangbuoc_tenphong_unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201409050519422_gobo_rangbuoc_tenphong_unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
