// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class them_subId_macdinh_moi_doi_tuong_phai_co__them_subId_macdinh_moi_doi_tuong_phai_co : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_subId_macdinh_moi_doi_tuong_phai_co__them_subId_macdinh_moi_doi_tuong_phai_co));
        
        string IMigrationMetadata.Id
        {
            get { return "201406271532533_them_subId_macdinh_moi_doi_tuong_phai_co__them_subId_macdinh_moi_doi_tuong_phai_co"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
