// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Them_nghiepVu_muonPhong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Them_nghiepVu_muonPhong));
        
        string IMigrationMetadata.Id
        {
            get { return "201408040805353_Them_nghiepVu_muonPhong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
