// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class sua_moi_quanhe_SUCOPHONG_LOGSUCOPHONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_moi_quanhe_SUCOPHONG_LOGSUCOPHONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201407161530183_sua_moi_quanhe_SUCOPHONG_LOGSUCOPHONG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
