// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class them_mota_cho_mot_vai_doiTuong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_mota_cho_mot_vai_doiTuong));
        
        string IMigrationMetadata.Id
        {
            get { return "201406110444009_them_mota_cho_mot_vai_doiTuong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
