// <auto-generated />
namespace QuanLyTaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class QLTSCD_xoa_rangbuoc_ctts_logts_chuthe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLTSCD_xoa_rangbuoc_ctts_logts_chuthe));
        
        string IMigrationMetadata.Id
        {
            get { return "201409040531083_QLTSCD_xoa_rangbuoc_ctts_logts_chuthe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
