//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTB_WEB.UserControl.LogThietBi {
    
    
    public partial class ucLogThietBi_BreadCrumb {
        
        /// <summary>
        /// _ucTimKiem_Mobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PTB_WEB.UserControl.Search.ucTimKiem_Mobile _ucTimKiem_Mobile;
        
        /// <summary>
        /// Label_TenThietBi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::System.Web.UI.WebControls.Label Label_TenThietBi;
        
        /// <summary>
        /// Label_LogNgay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::System.Web.UI.WebControls.Label Label_LogNgay;
    }
}
