SELECT       CTTHIETBIS.id as idCTTB, LOAITHIETBIS.ten as tenloaitb, CTTHIETBIS.soluong, TINHTRANGS.value, PHONGS.ten as tenphong, VITRIS.tang_id, VITRIS.day_id, COSOS.ten as tencs
FROM            CTTHIETBIS
INNER JOIN PHONGS ON (CTTHIETBIS.phong_id= PHONGS.id)
INNER JOIN VITRIS ON (PHONGS.vitri_id = VITRIS.id)
LEFT OUTER JOIN COSOS ON (VITRIS.coso_id = COSOS.id)
LEFT OUTER JOIN DAYS ON (VITRIS.day_id = DAYS.id)
LEFT OUTER JOIN TANGS ON (VITRIS.tang_id = TANGS.id)
INNER JOIN THIETBIS ON (THIETBIS.id = CTTHIETBIS.thietbi_id)
INNER JOIN LOAITHIETBIS ON (THIETBIS.loaithietbi_id = LOAITHIETBIS.id)
INNER JOIN TINHTRANGS ON (CTTHIETBIS.tinhtrang_id = TINHTRANGS.id)