SELECT       CTTHIETBIS.id as idCTTB, LOAITHIETBIS.ten as tenloaitb, CTTHIETBIS.soluong, TINHTRANGS.value, PHONGS.ten as tenphong, VITRIS.tang_id, VITRIS.day_id, COSOS.ten as tencs
FROM            PHONGS
INNER JOIN VITRIS ON PHONGS.vitri_id = VITRIS.id
LEFT OUTER JOIN COSOS ON (VITRIS.coso_id = COSOS.id)
INNER JOIN CTTHIETBIS ON (CTTHIETBIS.phong_id = PHONGS.id)
LEFT OUTER JOIN THIETBIS ON (THIETBIS.id = CTTHIETBIS.thietbi_id)
LEFT OUTER JOIN LOAITHIETBIS ON (THIETBIS.loaithietbi_id = LOAITHIETBIS.id)
LEFT OUTER JOIN TINHTRANGS ON (CTTHIETBIS.tinhtrang_id = TINHTRANGS.id)

LEFT OUTER JOIN TANGS ON (VITRIS.tang_id = TANGS.id)