//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY
    {
        public DAY()
        {
            this.TANGS = new HashSet<TANG>();
            this.VITRIS = new HashSet<VITRI>();
        }
    
        public System.Guid id { get; set; }
        public string ten { get; set; }
        public System.Guid coso_id { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual COSO COSO { get; set; }
        public virtual ICollection<TANG> TANGS { get; set; }
        public virtual ICollection<VITRI> VITRIS { get; set; }
    }
}
