//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public HINHANH()
        {
            this.COSOS = new HashSet<COSO>();
            this.CTTHIETBIS = new HashSet<CTTHIETBI>();
            this.DAYS = new HashSet<DAY>();
            this.LOGSUCOPHONGS = new HashSet<LOGSUCOPHONG>();
            this.LOGTHIETBIS = new HashSet<LOGTHIETBI>();
            this.NHANVIENPTS = new HashSet<NHANVIENPT>();
            this.PHONGS = new HashSet<PHONG>();
            this.SUCOPHONGS = new HashSet<SUCOPHONG>();
            this.TANGS = new HashSet<TANG>();
            this.THIETBIS = new HashSet<THIETBI>();
        }
    
        public System.Guid id { get; set; }
        public string path { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ICollection<COSO> COSOS { get; set; }
        public virtual ICollection<CTTHIETBI> CTTHIETBIS { get; set; }
        public virtual ICollection<DAY> DAYS { get; set; }
        public virtual ICollection<LOGSUCOPHONG> LOGSUCOPHONGS { get; set; }
        public virtual ICollection<LOGTHIETBI> LOGTHIETBIS { get; set; }
        public virtual ICollection<NHANVIENPT> NHANVIENPTS { get; set; }
        public virtual ICollection<PHONG> PHONGS { get; set; }
        public virtual ICollection<SUCOPHONG> SUCOPHONGS { get; set; }
        public virtual ICollection<TANG> TANGS { get; set; }
        public virtual ICollection<THIETBI> THIETBIS { get; set; }
    }
}
