//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHIETBI
    {
        public LOAITHIETBI()
        {
            this.LOAITHIETBIS1 = new HashSet<LOAITHIETBI>();
            this.THIETBIS = new HashSet<THIETBI>();
        }
    
        public System.Guid id { get; set; }
        public string ten { get; set; }
        public bool loaichung { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ICollection<LOAITHIETBI> LOAITHIETBIS1 { get; set; }
        public virtual LOAITHIETBI LOAITHIETBI1 { get; set; }
        public virtual ICollection<THIETBI> THIETBIS { get; set; }
    }
}
