//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITAISAN
    {
        public LOAITAISAN()
        {
            this.LOAITAISANS1 = new HashSet<LOAITAISAN>();
            this.TAISANS = new HashSet<TAISAN>();
        }
    
        public System.Guid id { get; set; }
        public bool huuhinh { get; set; }
        public string ten { get; set; }
        public int sonamsudung { get; set; }
        public int phantramhaomon { get; set; }
        public Nullable<System.Guid> donvitinh_id { get; set; }
        public Nullable<System.Guid> parent_id { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual ICollection<LOAITAISAN> LOAITAISANS1 { get; set; }
        public virtual LOAITAISAN LOAITAISAN1 { get; set; }
        public virtual ICollection<TAISAN> TAISANS { get; set; }
    }
}
