//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUONPHONG
    {
        public System.Guid id { get; set; }
        public string donvi { get; set; }
        public System.DateTime ngaymuon { get; set; }
        public System.DateTime ngaytra { get; set; }
        public string lydomuon { get; set; }
        public string ghichu { get; set; }
        public int trangthai { get; set; }
        public string lop { get; set; }
        public int sophong { get; set; }
        public System.Guid nguoimuon_id { get; set; }
        public Nullable<System.Guid> nguoiduyet_id { get; set; }
        public int soluongsv { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual QUANTRIVIEN QUANTRIVIEN { get; set; }
        public virtual QUANTRIVIEN QUANTRIVIEN1 { get; set; }
    }
}
