//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG
    {
        public TINHTRANG()
        {
            this.CTTAISANS = new HashSet<CTTAISAN>();
            this.LOGTAISANS = new HashSet<LOGTAISAN>();
        }
    
        public System.Guid id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ICollection<CTTAISAN> CTTAISANS { get; set; }
        public virtual ICollection<LOGTAISAN> LOGTAISANS { get; set; }
    }
}
