//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COSO> COSOS { get; set; }
        public virtual DbSet<CTTAISAN> CTTAISANS { get; set; }
        public virtual DbSet<DAY> DAYS { get; set; }
        public virtual DbSet<DONVI> DONVIS { get; set; }
        public virtual DbSet<DONVITINH> DONVITINHS { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<LOAIDONVI> LOAIDONVIS { get; set; }
        public virtual DbSet<LOAIPHONG> LOAIPHONGS { get; set; }
        public virtual DbSet<LOAITAISAN> LOAITAISANS { get; set; }
        public virtual DbSet<LOGHETHONG> LOGHETHONGS { get; set; }
        public virtual DbSet<LOGTAISAN> LOGTAISANS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<PHONG> PHONGS { get; set; }
        public virtual DbSet<QUANTRIVIEN> QUANTRIVIENS { get; set; }
        public virtual DbSet<SETTING> SETTINGS { get; set; }
        public virtual DbSet<TAISAN> TAISANS { get; set; }
        public virtual DbSet<TANG> TANGS { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGS { get; set; }
        public virtual DbSet<VITRI> VITRIS { get; set; }
    }
}
