//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHYSICAL_DB_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VITRI
    {
        public VITRI()
        {
            this.CTTAISANS = new HashSet<CTTAISAN>();
            this.LOGTAISANS = new HashSet<LOGTAISAN>();
            this.PHONGS = new HashSet<PHONG>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid coso_id { get; set; }
        public Nullable<System.Guid> day_id { get; set; }
        public Nullable<System.Guid> tang_id { get; set; }
        public string subId { get; set; }
        public Nullable<long> order { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual COSO COSO { get; set; }
        public virtual ICollection<CTTAISAN> CTTAISANS { get; set; }
        public virtual DAY DAY { get; set; }
        public virtual ICollection<LOGTAISAN> LOGTAISANS { get; set; }
        public virtual ICollection<PHONG> PHONGS { get; set; }
        public virtual TANG TANG { get; set; }
    }
}
